{
    'name': 'Meta Ads CRM & Lead Connector',
    'version': '19.0.1.3.1',
    'category': 'Sales/CRM',
    'summary': 'Connect Meta Lead Ads with Odoo CRM using OAuth, Webhooks and Lead Forms',
    'author': 'Recent Technologies',
    'website': 'mailto:rajodoodevelop@gmail.com',
    'support': 'rajodoodevelop@gmail.com',
    'license': 'LGPL-3',
    'depends': ['base', 'crm', 'mail', 'utm', 'web'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/ir_config_parameter.xml',
        'data/ir_cron.xml',
        'views/res_config_settings_views.xml',
        'views/meta_page_views.xml',
        'views/meta_lead_log_views.xml',
        'views/meta_form_views.xml',
        'views/meta_post_views.xml',
        'views/meta_promotion_views.xml',
        'views/crm_lead_views.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/banner.gif', 'static/description/icon.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'description': '',
}
